/* Studio OS — data: constants, scripts (incl. SMS), playbook */

var STAGES = ['Found','Contacted','Demo Sent','Discovery','Proposal','Signed'];
var STAGE_PROB = {'Found':0.10,'Contacted':0.25,'Demo Sent':0.50,'Discovery':0.65,'Proposal':0.80,'Signed':1.00};
var CLIENT_STAGES = ['Content','Build','Round 1','Round 2','Launch','Done'];
var LOST_REASONS = ['Ghosted','Price too high','Timing not right','Went with someone else','DIY','Not interested','Could not reach decision maker','Other'];

var DEFAULT_CHECKLIST = [
'Repo created from template',
'Content received (photos, text, hours, phone, email)',
'Contact form formapi_email set',
'Form tested',
'Placeholder images replaced',
'Title tag + meta description updated',
'Local business JSON-LD added',
'robots.txt + sitemap.xml at root',
'Favicon set',
'Deployed to Cloudflare Pages',
'Custom domain connected (www + non-www)',
'SSL verified',
'Google Business Profile set up',
'Analytics installed',
'Search Console property added',
'Sitemap submitted',
'Handover email sent',
'30-day bug window logged',
'Retainer offer sent'
];

var DEFAULT_OUTREACH = {
email: { subject:'Quick question about {business}', body:'Hi {name},\n\nI build websites for local {industry} businesses{city_clause}. I noticed {business} {demo_clause}.\n\n{demo_line}\n\nTakes 30 seconds to look at. No charge, no obligation.\n\nIf you like it, I can have it live on your own domain in a week or two. If not, no hard feelings.\n\n- {me_name}\n{me_phone}' },
text: { body:'Hi {name} - this is {me_name}. I build websites for local {industry} businesses. I put together a quick preview of what a modern site for {business} could look like. Want the link? No charge, no obligation.' },
wa: { body:'Hi {name}! {me_name} here. I build websites for local {industry} businesses. I noticed {business} and put together a quick preview - want the link? No charge, no obligation.' }
};

var DEFAULT_SCRIPTS = [
{id:'cold-call',category:'outreach',title:'Cold call - opening',body:'"Hi, is this {name}?\n\nHey {name}, this is {me_name} - I build websites for local {industry} businesses here in {city}.\n\nI noticed {business} does not have a website listed / has one that is a bit dated. So I put together a quick preview of what a modern version could look like - takes about 15 minutes to build, no charge, no obligation.\n\nWant me to send you the link so you can have a look? If you like it, we can talk. If not, no hard feelings."'},
{id:'cold-email',category:'outreach',title:'Cold email - first touch',body:'Subject: Quick question about {business}\n\nHi {name},\n\nI build websites for local {industry} businesses in {city}. I noticed {business} does not have a site (or the current one looks dated).\n\nI put together a preview of what a modern version could look like:\n{demo}\n\nTakes 30 seconds to look at. No charge, no obligation.\n\n- {me_name}\n{me_phone}'},
{id:'cold-sms',category:'outreach',title:'Cold text - first touch (SMS)',body:'Hi {name} - this is {me_name}. I build websites for local {industry} businesses. I put together a quick preview of a modern site for {business}. Want the link? No charge, no obligation.'},
{id:'cold-wa',category:'outreach',title:'Cold WhatsApp - first touch',body:'Hi {name}! {me_name} here. I build websites for local {industry} businesses. I noticed {business} and put together a quick preview - want the link? No charge, no obligation.'},
{id:'followup3-email',category:'outreach',title:'Follow-up email (day 3)',body:'Subject: Re: Quick question about {business}\n\nHi {name},\n\nJust following up on the preview I sent for {business}. Have you had a chance to look?\n\nHappy to walk you through it.\n\n- {me_name}'},
{id:'followup3-sms',category:'outreach',title:'Follow-up text (day 3, SMS)',body:'Hi {name} - just circling back on the preview I sent for {business}. Worth a look? No pressure either way. - {me_name}'},
{id:'followup7',category:'outreach',title:'Follow-up (day 7 - final nudge)',body:'Hi {name},\n\nLast note on this - do not want to keep bugging you. If the timing is not right for the {business} website, just say the word and I will close the file.\n\nIf you do want it, I can have it live in about 2 weeks.\n\n- {me_name}'},
{id:'voicemail',category:'outreach',title:'Voicemail script',body:'"Hi {name}, this is {me_name} - I build websites for local {industry} businesses in {city}.\n\nI made a quick preview of a modern site for {business} and I would love to send you the link. No charge, no obligation.\n\nMy number is {me_phone}. I will try again in a couple of days. Thanks!"'},
{id:'discovery',category:'calls',title:'Discovery call questions',body:'1. What does the business do - and who is the typical customer?\n2. What is the main reason you are looking at a website now?\n3. What do you want the site to actually do?\n4. What is wrong with your current setup?\n5. Do you have photos and text ready?\n6. Who approves changes on your side?\n7. What is your timeline?\n8. What is your budget for this?\n9. Have you worked with a web person before?\n10. Anything else I should know?'},
{id:'objection-price',category:'calls',title:'Objection - too expensive',body:'"I hear you. Let me be straight about what is in the price - this is not just a template. It includes the site built with your content, hosting set up, domain connected, SSL, Google Business Profile, analytics, and 30 days of bug fixes. That is a complete package.\n\nIf the full thing does not fit your budget right now, I can do a lighter version - just the site and form - for less. Want me to walk you through the two options?"'},
{id:'objection-time',category:'calls',title:'Objection - let me think about it',body:'"Absolutely. While you think - just so we do not go back and forth - what is the one thing you are unsure about? Price, timing, or whether it is the right move?\n\nIf I can answer that now, it might make the decision easier. If you still want time, I will follow up in a week."'},
{id:'proposal-email',category:'proposals',title:'Proposal email',body:'Subject: Proposal - {business} website\n\nHi {name},\n\nThanks for the call earlier. Here is the proposal we discussed.\n\nSCOPE\n- Custom {industry} website - 6 pages\n- Your real content\n- Contact form wired to your email\n- Hosting on Cloudflare Pages\n- Custom domain + SSL\n- Google Business Profile setup\n- Analytics installed\n- 30 days of bug fixes\n\nPRICE\n{price}\n\nTERMS\n- 50% deposit to begin, 50% on launch\n- 2 rounds of revisions\n- After 30 days, changes billed at {hourly}/hour\n\n- {me_name}'},
{id:'retainer',category:'post-launch',title:'Retainer offer (at launch)',body:'Subject: Site is live - quick note about updates\n\nHi {name},\n\nYour site is live. Anything look off? Reply and I will fix it - you have 30 days of bug fixes included.\n\nOne more thing: if you want me to keep it updated, I offer a monthly plan.\n\n{retainer}/month covers:\n- Hosting management\n- Security updates\n- Small content changes\n- Priority support\n\nNo contract. Cancel any time.\n\n- {me_name}'},
{id:'handover',category:'post-launch',title:'Handover doc (client-facing)',body:'Your Website - Handover Guide\n\nLIVE URL: [https://yoursite.com]\n\nHOW TO MAKE CHANGES\nSmall changes: reply to this email (free for 30 days).\nLarger changes: I will quote them individually.\n\nTHE TECHNOLOGY\n- Single HTML file\n- Hosted on Cloudflare Pages\n- Form emails go to: [their email]\n\nWHAT IS COVERED (30 days)\nBroken links, form issues, display bugs\n\nWHAT IS NOT COVERED\nNew pages, major redesigns, content changes after 30 days\n\nCONTACT\n{me_name} - {me_email} - {me_phone}'},
{id:'checkin-30',category:'post-launch',title:'30-day check-in',body:'Subject: 30 days in - how is the site?\n\nHi {name},\n\nIt has been 30 days since your site launched. Anything you would change? Anything broken?\n\n- Are you getting calls from the site?\n- Anything you wish worked differently?\n- Do you want me to keep it updated?\n\n- {me_name}'},
{id:'feedback',category:'post-launch',title:'Feedback request (30/90 day)',body:'Subject: Quick favor - two questions about the site\n\nHi {name},\n\nHope the site is working well. Two quick questions:\n\n1. On a scale of 0-10, how likely are you to recommend me to another business owner?\n2. What is one thing I could do better?\n\n- {me_name}'},
{id:'payment-reminder',category:'admin',title:'Payment reminder (gentle)',body:'Subject: Quick nudge - invoice #[ref]\n\nHi {name},\n\nJust a friendly reminder that invoice #[ref] for $[amount] is still open. Payoneer reference is [PAY-XXXX].\n\nNo rush if you are mid-week - just flagging so it does not get lost.\n\n- {me_name}'},
{id:'payment-reminder-sms',category:'admin',title:'Payment reminder (SMS)',body:'Hi {name} - quick nudge on invoice #[ref] for $[amount]. Payoneer ref [PAY-XXXX]. No rush. - {me_name}'},
{id:'scope-creep',category:'admin',title:'Scope creep response',body:'Hi {name},\n\nHappy to do that - but it is outside the original scope we agreed on.\n\nTwo options:\n1. I can quote it as a one-off: about $[X] for [change], takes [Y days]\n2. Add it to a monthly retainer ({retainer}/mo) and I will fold it in over time\n\nLet me know which works better.\n\n- {me_name}'},
{id:'nonpayment',category:'admin',title:'Non-payment escalation',body:'Subject: Final notice - invoice #[ref]\n\nHi {name},\n\nThis is a follow-up on invoice #[ref] for $[amount], open since [date].\n\nPer our agreement, payment was due [X days] ago. Please arrange it within 5 business days.\n\nIf there is an issue I should know about, reply and let me know.\n\n- {me_name}'}
];

var PLAYBOOK = [
{id:'quickstart',title:'0. Quick start - first hour',body:'<p>Do these in order. Takes about 60 minutes.</p><h4>1. Set up accounts (30 min)</h4><ol><li><strong>GitHub</strong> - github.com - sign up</li><li><strong>Cloudflare</strong> - dash.cloudflare.com - sign up</li><li><strong>Payoneer</strong> - payoneer.com - sign up, submit ID (2-5 days)</li><li><strong>Gumroad</strong> - for taking deposits</li><li>Bookmark <strong>formapi.xyz</strong></li></ol><h4>2. Fill in Settings (5 min)</h4><p>Enter name, email, phone, brand, rates.</p><h4>3. Prep your template repo (15 min)</h4><ol><li>Build one site you are proud of</li><li>Push to private GitHub repo <code>site-template-v1</code></li><li>Turn on "Template repository" in settings</li></ol><h4>4. Test the pipeline once (10 min)</h4><ol><li>Add a fake lead</li><li>Deploy a demo to Cloudflare Pages</li><li>Send yourself the outreach email</li><li>Convert the lead to a client</li><li>Generate an invoice, print it, delete everything</li></ol><div class="callout ok">Once you can do all of that in 10 minutes, you are ready to sell.</div>'},
{id:'accounts',title:'1. Account setup',body:'<h4>Required</h4><ol><li><strong>GitHub</strong> - free, unlimited repos</li><li><strong>Cloudflare</strong> - Pages, DNS, SSL, analytics</li><li><strong>Payoneer</strong> - free, US receiving account</li><li><strong>Gumroad</strong> - deposits without a company</li><li><strong>FormAPI</strong> (formapi.xyz) - no signup</li><li><strong>Google Business Profile</strong> - per client</li></ol><div class="callout warn"><strong>Payoneer tip:</strong> Use your real legal name exactly as on your ID.</div>'},
{id:'github',title:'2. GitHub workflow',body:'<h4>Create template repo (once)</h4><ol><li>New repository - <code>site-template-v1</code></li><li>Private, initialize with README</li><li>Upload template HTML</li><li>Settings - Template repository - ON</li></ol><h4>Per client</h4><ol><li>Open template repo</li><li><strong>Use this template</strong> - Create new repo</li><li>Name <code>client-slug</code>, keep private</li><li>Edit content, commit</li></ol><div class="callout">Keep client repos <strong>private</strong>.</div>'},
{id:'cloudflare',title:'3. Cloudflare Pages',body:'<h4>First deploy</h4><ol><li>dash.cloudflare.com - Workers &amp; Pages - Create - Pages - Connect to Git</li><li>Authorize GitHub</li><li>Select repo</li><li>Build: framework None, command empty, output <code>/</code></li><li>Save and Deploy</li><li>Get URL <code>*.pages.dev</code></li></ol><h4>Custom domain</h4><ol><li>Client buys domain</li><li>Pages - Custom domains - Set up</li><li>Add www and non-www</li><li>If on Cloudflare DNS, automatic. Otherwise change nameservers or CNAME.</li><li>Wait 1-30 min for SSL</li></ol>'},
{id:'forms',title:'4. Contact forms (FormAPI)',body:'<p>Free service. POST to <code>https://formapi.xyz/submit</code>, emails you the result. No backend.</p><pre>&lt;form action="https://formapi.xyz/submit" method="POST"&gt;\n  &lt;input type="hidden" name="formapi_email" value="client@example.com"&gt;\n  &lt;input type="text" name="name" required&gt;\n  &lt;input type="email" name="email" required&gt;\n  &lt;textarea name="message" required&gt;&lt;/textarea&gt;\n  &lt;button type="submit"&gt;Send&lt;/button&gt;\n&lt;/form&gt;</pre><div class="callout">Check spam. Gmail may filter first-time emails.</div>'},
{id:'payments',title:'5. Getting paid',body:'<h4>Setup by situation</h4><ul><li><strong>No LLC, international:</strong> Gumroad</li><li><strong>Bank transfer:</strong> Payoneer</li><li><strong>PayPal:</strong> Fine, ~4% fees</li></ul><h4>50/50 rule</h4><p>Always take 50% upfront. Non-negotiable.</p><h4>Invoice flow</h4><ol><li>Client agrees to proposal</li><li>Send deposit invoice with Payoneer ref</li><li>Client pays - you begin</li><li>At launch, send final invoice</li><li>Client pays - you hand over</li></ol><div class="callout warn">Do not hand over final site or domain access until balance is paid.</div>'},
{id:'seo',title:'6. SEO essentials',body:'<h4>Baseline</h4><ul><li><strong>Title tag</strong> - "Business Name - Service in City"</li><li><strong>Meta description</strong> - 150-160 chars, location + service</li><li><strong>H1</strong> - one per page</li><li><strong>Alt text</strong> on every image</li><li><strong>JSON-LD</strong> local business schema</li><li><strong>robots.txt</strong> + <strong>sitemap.xml</strong></li></ul><h4>Local SEO</h4><ol><li>Claim Google Business Profile</li><li>Fill every field</li><li>Add site URL</li><li>Ask for 3-5 reviews</li></ol><div class="callout">Local SEO is 80% Google Business Profile + reviews.</div>'},
{id:'handover-pb',title:'7. Client handover',body:'<h4>Package</h4><ol><li>Write access to GitHub repo (or transfer)</li><li>Cloudflare project invitation</li><li>Domain registrar login</li><li>Handover doc (see Scripts)</li><li>30-day bug fix start date</li></ol><h4>Cloudflare Pages transfer</h4><ul><li>No direct transfer feature</li><li>Easiest: new client account - reconnect same repo - add domain - remove from yours</li><li>Or: keep on your account, bill monthly retainer</li></ul>'},
{id:'troubleshooting',title:'8. Troubleshooting',body:'<h4>Site broken</h4><ul><li>Check Cloudflare deploy log</li><li>Hard refresh (Cmd+Shift+R)</li><li>DevTools Console - red errors tell you</li></ul><h4>Form not submitting</h4><ul><li>action exactly <code>https://formapi.xyz/submit</code></li><li>formapi_email valid</li><li>Check spam</li></ul><h4>Domain not working</h4><ul><li><code>dig yourdomain.com</code></li><li>If resolving but error: not attached to Pages</li></ul>'},
{id:'pricing',title:'9. Pricing',body:'<h4>Packages</h4><ul><li><strong>Basic - $1,500.</strong> Single page, form, domain, 30 days.</li><li><strong>Standard - $2,000.</strong> 4-6 pages + GMB + analytics + sitemap.</li><li><strong>Premium - $2,800.</strong> + animations + copywriting + 90-day check-in.</li><li><strong>Retainer - $100/mo.</strong></li><li><strong>Hourly - $75/hr.</strong></li></ul><h4>When to raise</h4><ul><li>After 5 projects at current rate</li><li>When 3/5 say yes without hesitation</li><li>When booked 4+ weeks out</li></ul><div class="callout ok">Charge more. Clients respect a confident price.</div>'}
];
