/* Studio OS — data: constants, scripts (incl. SMS), playbook */

var STAGES = ['Found','Contacted','Demo Sent','Discovery','Proposal','Signed'];
var STAGE_PROB = {'Found':0.10,'Contacted':0.25,'Demo Sent':0.50,'Discovery':0.65,'Proposal':0.80,'Signed':1.00};
var CLIENT_STAGES = ['Content','Build','Round 1','Round 2','Launch','Done'];
var LOST_REASONS = ['Ghosted','Price too high','Timing not right','Went with someone else','DIY','Not interested','Could not reach decision maker','Other'];
var DEPLOY_TARGETS = ['staging','live'];
var DOMAIN_STATUS = ['pending','active','failed'];

/* Cloudflare-only checklist — replaces the old GitHub items */
var DEFAULT_CHECKLIST = [
  'Staging project created on Cloudflare Pages (Direct Upload)',
  'Local folder contains index.html, styles.css, data.js, app.js, features.js, commands.js',
  'Staging deployed — link tested on desktop + phone',
  'Contact form tested (formapi_email set correctly)',
  'Placeholder images + copy replaced with real client content',
  'Title tag + meta description updated',
  'Local business JSON-LD added',
  'robots.txt + sitemap.xml at project root',
  'Favicon set',
  'Promoted SAME folder to Live project',
  'Custom domain added (www + non-www)',
  'SSL active — padlock shows, no mixed-content warnings',
  'Cloudflare Web Analytics snippet installed',
  'Google Business Profile updated with live URL',
  '30-day bug window start date logged',
  'Handover email sent to client',
  'Retainer offer sent'
];

var DEFAULT_OUTREACH = {
email: { subject:'Quick question about {business}', body:'Hi {name},\n\nI build websites for local {industry} businesses{city_clause}. I noticed {business} {demo_clause}.\n\n{demo_line}\n\nTakes 30 seconds to look at. No charge, no obligation.\n\nIf you like it, I can have it live on your own domain in a week or two. If not, no hard feelings.\n\n- {me_name}\n{me_phone}' },
text: { body:'Hi {name} - this is {me_name}. I build websites for local {industry} businesses. I put together a quick preview of what a modern site for {business} could look like. Want the link? No charge, no obligation.' },
wa: { body:'Hi {name}! {me_name} here. I build websites for local {industry} businesses. I noticed {business} and put together a quick preview - want the link? No charge, no obligation.' }
};

var DEFAULT_SCRIPTS = [
{id:'cold-call',category:'outreach',title:'Cold call - opening',body:'"Hi, is this {name}?\n\nHey {name}, this is {me_name} - I build websites for local {industry} businesses here in {city}.\n\nI noticed {business} does not have a website listed / has one that is a bit dated. So I put together a quick preview of what a modern version could look like - takes about 15 minutes to build, no charge, no obligation.\n\nWant me to send you the link so you can have a look? If you like it, we can talk. If not, no hard feelings."'},
{id:'cold-email',category:'outreach',title:'Cold email - first touch',body:'Subject: Quick question about {business}\n\nHi {name},\n\nI build websites for local {industry} businesses in {city}. I noticed {business} does not have a site (or the current one looks dated).\n\nI put together a preview of what a modern version could look like:\n{demo}\n\nTakes 30 seconds to look at. No charge, no obligation.\n\n- {me_name}\n{me_phone}'},
{id:'cold-sms',category:'outreach',title:'Cold text - first touch (SMS)',body:'Hi {name} - this is {me_name}. I build websites for local {industry} businesses. I put together a quick preview of a modern site for {business}. Want the link? No charge, no obligation.'},
{id:'cold-wa',category:'outreach',title:'Cold WhatsApp - first touch',body:'Hi {name}! {me_name} here. I build websites for local {industry} businesses. I noticed {business} and put together a quick preview - want the link? No charge, no obligation.'},
{id:'followup3-email',category:'outreach',title:'Follow-up email (day 3)',body:'Subject: Re: Quick question about {business}\n\nHi {name},\n\nJust following up on the preview I sent for {business}. Have you had a chance to look?\n\nHappy to walk you through it.\n\n- {me_name}'},
{id:'followup3-sms',category:'outreach',title:'Follow-up text (day 3, SMS)',body:'Hi {name} - just circling back on the preview I sent for {business}. Worth a look? No pressure either way. - {me_name}'},
{id:'followup7',category:'outreach',title:'Follow-up (day 7 - final nudge)',body:'Hi {name},\n\nLast note on this - do not want to keep bugging you. If the timing is not right for the {business} website, just say the word and I will close the file.\n\nIf you do want it, I can have it live in about 2 weeks.\n\n- {me_name}'},
{id:'voicemail',category:'outreach',title:'Voicemail script',body:'"Hi {name}, this is {me_name} - I build websites for local {industry} businesses in {city}.\n\nI made a quick preview of a modern site for {business} and I would love to send you the link. No charge, no obligation.\n\nMy number is {me_phone}. I will try again in a couple of days. Thanks!"'},
{id:'discovery',category:'calls',title:'Discovery call questions',body:'1. What does the business do - and who is the typical customer?\n2. What is the main reason you are looking at a website now?\n3. What do you want the site to actually do?\n4. What is wrong with your current setup?\n5. Do you have photos and text ready?\n6. Who approves changes on your side?\n7. What is your timeline?\n8. What is your budget for this?\n9. Have you worked with a web person before?\n10. Anything else I should know?'},
{id:'objection-price',category:'calls',title:'Objection - too expensive',body:'"I hear you. Let me be straight about what is in the price - this is not just a template. It includes the site built with your content, hosting set up, domain connected, SSL, Google Business Profile, analytics, and 30 days of bug fixes. That is a complete package.\n\nIf the full thing does not fit your budget right now, I can do a lighter version - just the site and form - for less. Want me to walk you through the two options?"'},
{id:'objection-time',category:'calls',title:'Objection - let me think about it',body:'"Absolutely. While you think - just so we do not go back and forth - what is the one thing you are unsure about? Price, timing, or whether it is the right move?\n\nIf I can answer that now, it might make the decision easier. If you still want time, I will follow up in a week."'},
{id:'proposal-email',category:'proposals',title:'Proposal email',body:'Subject: Proposal - {business} website\n\nHi {name},\n\nThanks for the call earlier. Here is the proposal we discussed.\n\nSCOPE\n- Custom {industry} website - 6 pages\n- Your real content\n- Contact form wired to your email\n- Hosting on Cloudflare Pages\n- Custom domain + SSL\n- Google Business Profile setup\n- Analytics installed\n- 30 days of bug fixes\n\nPRICE\n{price}\n\nTERMS\n- 50% deposit to begin, 50% on launch\n- 2 rounds of revisions\n- After 30 days, changes billed at {hourly}/hour\n\n- {me_name}'},
{id:'retainer',category:'post-launch',title:'Retainer offer (at launch)',body:'Subject: Site is live - quick note about updates\n\nHi {name},\n\nYour site is live. Anything look off? Reply and I will fix it - you have 30 days of bug fixes included.\n\nOne more thing: if you want me to keep it updated, I offer a monthly plan.\n\n{retainer}/month covers:\n- Hosting management\n- Security updates\n- Small content changes\n- Priority support\n\nNo contract. Cancel any time.\n\n- {me_name}'},
{id:'handover',category:'post-launch',title:'Handover doc (client-facing)',body:'Your Website - Handover Guide\n\nLIVE URL: {demo}\n\nHOW TO MAKE CHANGES\nSmall changes: reply to this email (free for 30 days).\nLarger changes: I will quote them individually.\n\nTHE TECHNOLOGY\n- HTML/CSS/JS, single-folder site\n- Hosted on Cloudflare Pages\n- Form emails go to: [their email]\n\nWHAT IS COVERED (30 days)\nBroken links, form issues, display bugs\n\nWHAT IS NOT COVERED\nNew pages, major redesigns, content changes after 30 days\n\nCONTACT\n{me_name} - {me_email} - {me_phone}'},
{id:'checkin-30',category:'post-launch',title:'30-day check-in',body:'Subject: 30 days in - how is the site?\n\nHi {name},\n\nIt has been 30 days since your site launched. Anything you would change? Anything broken?\n\n- Are you getting calls from the site?\n- Anything you wish worked differently?\n- Do you want me to keep it updated?\n\n- {me_name}'},
{id:'feedback',category:'post-launch',title:'Feedback request (30/90 day)',body:'Subject: Quick favor - two questions about the site\n\nHi {name},\n\nHope the site is working well. Two quick questions:\n\n1. On a scale of 0-10, how likely are you to recommend me to another business owner?\n2. What is one thing I could do better?\n\n- {me_name}'},
{id:'payment-reminder',category:'admin',title:'Payment reminder (gentle)',body:'Subject: Quick nudge - invoice #[ref]\n\nHi {name},\n\nJust a friendly reminder that invoice #[ref] for $[amount] is still open. Payoneer reference is [PAY-XXXX].\n\nNo rush if you are mid-week - just flagging so it does not get lost.\n\n- {me_name}'},
{id:'payment-reminder-sms',category:'admin',title:'Payment reminder (SMS)',body:'Hi {name} - quick nudge on invoice #[ref] for $[amount]. Payoneer ref [PAY-XXXX]. No rush. - {me_name}'},
{id:'scope-creep',category:'admin',title:'Scope creep response',body:'Hi {name},\n\nHappy to do that - but it is outside the original scope we agreed on.\n\nTwo options:\n1. I can quote it as a one-off: about $[X] for [change], takes [Y days]\n2. Add it to a monthly retainer ({retainer}/mo) and I will fold it in over time\n\nLet me know which works better.\n\n- {me_name}'},
{id:'nonpayment',category:'admin',title:'Non-payment escalation',body:'Subject: Final notice - invoice #[ref]\n\nHi {name},\n\nThis is a follow-up on invoice #[ref] for $[amount], open since [date].\n\nPer our agreement, payment was due [X days] ago. Please arrange it within 5 business days.\n\nIf there is an issue I should know about, reply and let me know.\n\n- {me_name}'}
];

var PLAYBOOK = [
{id:'quickstart',title:'0. Quick start - first hour',body:'<p>Cloudflare-only workflow. No GitHub, no build step. Do these in order - takes about 60 minutes.</p><h4>1. Accounts (20 min)</h4><ol><li><strong>Cloudflare</strong> - dash.cloudflare.com - sign up</li><li><strong>Payoneer</strong> - payoneer.com - submit ID (2-5 days)</li><li><strong>Gumroad</strong> - for deposits without a company</li><li>Bookmark <strong>formapi.xyz</strong></li><li>Bookmark <strong>jsonbin.io</strong> (for optional sync)</li></ol><h4>2. Build one demo site (30 min)</h4><ol><li>Create a folder with <code>index.html</code> + your template CSS</li><li>Test it locally by double-clicking index.html</li><li>Go to Cloudflare - Workers &amp; Pages - Create - Pages - Direct Upload</li><li>Name it <code>demo-roofing</code>, drop the folder, deploy</li><li>You now have a public URL: <code>demo-roofing.pages.dev</code></li></ol><h4>3. Settings in Studio OS (5 min)</h4><p>Enter name, email, phone, brand, rates.</p><h4>4. Test the pipeline (5 min)</h4><ol><li>Add a fake lead</li><li>Deploy a demo to Cloudflare Pages</li><li>Paste the URL into the lead - it should open in a new tab when tapped</li><li>Convert to client, generate a deposit invoice</li></ol><div class="callout ok">Once you can do all of that in 45 minutes, you are ready to sell.</div>'},
{id:'cloudflare',title:'1. Cloudflare Pages - the only hosting you need',body:'<h4>Why Cloudflare</h4><ul><li>Free unlimited hosting + SSL</li><li>Global CDN, loads under 1 second</li><li>Direct Upload = no GitHub, no build step</li><li>You can never "break" a live site - failed deploys are ignored, live stays on last good version</li></ul><h4>The two-project rule (memorize this)</h4><ol><li><code>clientname</code> = LIVE (what customers see)</li><li><code>clientname-staging</code> = COPY (where you break stuff safely)</li></ol><h4>Every change flow</h4><ol><li>Edit locally</li><li>Dashboard - <code>clientname-staging</code> - Create new deployment - upload folder</li><li>Test the <code>.pages.dev</code> URL on phone + desktop</li><li>Only when perfect - upload the SAME folder to <code>clientname</code></li><li>Live updates in ~30 seconds</li></ol><div class="callout warn">Never upload directly to the live project. Always staging first.</div>'},
{id:'domains',title:'2. Domains + CNAME - how it actually works',body:'<h4>A) Client bought domain on Cloudflare (BEST)</h4><ol><li>Client buys domain at cloudflare.com (~$10/yr)</li><li>Pages - Project <code>clientname</code> - Custom domains</li><li>Add <code>clientname.com</code> + <code>www.clientname.com</code></li><li>Cloudflare does everything. SSL in ~2 minutes.</li></ol><h4>B) Client domain elsewhere (GoDaddy, Namecheap)</h4><p><strong>Option 1 (push for this) - full Cloudflare:</strong></p><ol><li>Cloudflare - Add site - enter domain</li><li>Cloudflare gives 2 nameservers</li><li>Client changes nameservers at their registrar</li><li>Now custom domain setup is 1-click</li></ol><p><strong>Option 2 - CNAME only (messier):</strong></p><ul><li><code>www</code> - CNAME - <code>clientname.pages.dev</code></li><li>Root <code>@</code> usually cannot be a CNAME - redirect root to www in Cloudflare</li><li>Pages - Custom domains - add <code>www.clientname.com</code></li></ul><div class="callout">Never ask for a client Cloudflare password. Ask them to invite your email under Account - Members - Invite - Administrator. Professional and revocable.</div>'},
{id:'forms',title:'3. Contact forms (FormAPI)',body:'<p>Free service. POST to <code>https://formapi.xyz/submit</code>, emails the result. No backend needed.</p><pre>&lt;form action="https://formapi.xyz/submit" method="POST"&gt;\n  &lt;input type="hidden" name="formapi_email" value="client@example.com"&gt;\n  &lt;input type="text" name="name" required&gt;\n  &lt;input type="email" name="email" required&gt;\n  &lt;textarea name="message" required&gt;&lt;/textarea&gt;\n  &lt;button type="submit"&gt;Send&lt;/button&gt;\n&lt;/form&gt;</pre><div class="callout">Check spam. Gmail may filter first-time emails until the client marks "not spam".</div>'},
{id:'analytics',title:'4. Analytics, robots.txt, sitemap - no Google needed',body:'<h4>Cloudflare Web Analytics (no cookie banner)</h4><ol><li>Cloudflare Dashboard - Web Analytics - Add site</li><li>Copy the JS snippet</li><li>Paste before <code>&lt;/body&gt;</code> in index.html</li><li>Redeploy both staging + live</li></ol><p>Shows visits, top pages, countries, referrers. Give the client viewer access - they love it.</p><h4>robots.txt</h4><pre>User-agent: *\nAllow: /\nSitemap: https://clientname.com/sitemap.xml</pre><h4>sitemap.xml</h4><p>Use xml-sitemaps.com, download, drop in project root. Cloudflare serves it automatically.</p>'},
{id:'payments',title:'5. Getting paid',body:'<h4>Setup by situation</h4><ul><li><strong>No LLC, international:</strong> Gumroad</li><li><strong>Bank transfer:</strong> Payoneer</li><li><strong>PayPal:</strong> Fine, ~4% fees</li></ul><h4>The 50/50 rule</h4><p>Always take 50% upfront. Non-negotiable. No deposit, no build.</p><h4>Invoice flow</h4><ol><li>Client agrees to proposal</li><li>Send deposit invoice with Payoneer ref</li><li>Client pays - you begin</li><li>At launch, send final invoice</li><li>Client pays - you hand over</li></ol><div class="callout warn">Do not hand over domain access or the Cloudflare project until the final balance is paid.</div>'},
{id:'seo',title:'6. SEO essentials',body:'<h4>Baseline per site</h4><ul><li><strong>Title tag</strong> - "Business Name - Service in City"</li><li><strong>Meta description</strong> - 150-160 chars, location + service</li><li><strong>H1</strong> - one per page</li><li><strong>Alt text</strong> on every image</li><li><strong>JSON-LD</strong> LocalBusiness schema</li><li><strong>robots.txt</strong> + <strong>sitemap.xml</strong></li></ul><h4>Local SEO</h4><ol><li>Claim Google Business Profile</li><li>Fill every field - hours, phone, services</li><li>Add site URL</li><li>Ask for 3-5 reviews in the first month</li></ol><div class="callout">Local SEO is 80% Google Business Profile + reviews. The website just needs to not be embarrassing.</div>'},
{id:'handover-pb',title:'7. Client handover',body:'<h4>Package</h4><ol><li>Live URL, working padlock</li><li>Cloudflare project invite (or keep on your account with retainer)</li><li>Domain registrar login</li><li>Handover doc (see Scripts - "Handover doc")</li><li>30-day bug fix start date logged</li></ol><h4>Two ways to hand over Cloudflare</h4><ul><li><strong>Retainer model (recommended):</strong> Keep the Pages project on your account. Charge $100/mo. You stay in control, client can leave anytime.</li><li><strong>Full handover:</strong> Client creates their own Cloudflare account, invites you, you re-upload the same folder into their account, add the domain there, delete from yours.</li></ul>'},
{id:'troubleshooting',title:'8. Troubleshooting',body:'<h4>Site broken after upload</h4><ul><li>Cloudflare keeps serving the last good deploy. It never goes fully down.</li><li>Check the deploy log in Cloudflare for build errors (rare with Direct Upload)</li><li>Hard refresh: Cmd+Shift+R / Ctrl+Shift+R</li><li>Open DevTools Console - red lines tell you what is missing</li></ul><h4>Form not submitting</h4><ul><li><code>action</code> exactly <code>https://formapi.xyz/submit</code></li><li><code>formapi_email</code> hidden input is valid</li><li>Check spam - and Gmail "All Mail"</li></ul><h4>Domain not working</h4><ul><li><code>dig yourdomain.com</code> in terminal</li><li>If it resolves but shows error - domain is not attached to the Pages project</li><li>If it does not resolve - nameservers not propagated yet (wait 30-60 min)</li></ul>'},
{id:'pricing',title:'9. Pricing',body:'<h4>Packages</h4><ul><li><strong>Basic - $1,500.</strong> Single page, form, domain, 30 days.</li><li><strong>Standard - $2,000.</strong> 4-6 pages + GMB + analytics + sitemap.</li><li><strong>Premium - $2,800.</strong> + animations + copywriting + 90-day check-in.</li><li><strong>Retainer - $100/mo.</strong></li><li><strong>Hourly - $75/hr.</strong></li></ul><h4>When to raise prices</h4><ul><li>After 5 projects at current rate</li><li>When 3/5 say yes without hesitation</li><li>When booked 4+ weeks out</li></ul><div class="callout ok">Charge more. Clients respect a confident price.</div>'}
];

/* Help system — describes every section */
var HELP_SECTIONS = [
{id:'today', title:'Today', body:'Your daily driver. Everything that needs you right now: overdue tasks, leads going cold, invoices to chase, retainers to bill, check-ins due, and (new) staging deploys ready to promote. If this page is empty, you have nothing to do — go find leads.'},
{id:'dashboard', title:'Dashboard', body:'The bird\'s-eye view. Revenue collected this year, weighted pipeline value (probability-adjusted), open leads, retainers, a 12-month revenue chart, and a source-performance chart. Use this weekly to see if your business is actually growing.'},
{id:'leads', title:'Leads', body:'Your kanban board. Six columns: Found → Contacted → Demo Sent → Discovery → Proposal → Signed. Click any card to open the lead. Every card has Mail / SMS / WA buttons for one-tap outreach. Tags show value, next-action date, staleness, and demo URL (now clickable).'},
{id:'clients', title:'Clients', body:'Active paying clients. Each row shows stage, checklist progress, package price, retainer status, and quick action buttons for opening staging/live URLs. Click any row to open the full client — Cloudflare project name, staging URL, live URL, domain status, deploy log, checklist, and shortcuts to generate invoices or log time.'},
{id:'proposals', title:'Proposals', body:'Every proposal you have sent. Status flow: Draft → Sent → Viewed → Accepted or Declined. Print a proposal to PDF straight from the browser. Declining captures a reason so you can spot patterns in why deals die.'},
{id:'invoices', title:'Invoices', body:'All invoices — deposits, finals, retainers, hourly. Status: Pending → Paid. Overdue invoices auto-flag based on your overdue threshold in Settings. Retainer invoices auto-generate on the billing day you set.'},
{id:'deployments', title:'Deployments', body:'NEW. A full log of every staging and live upload you have done, per client. Filter by client, see target (staging/live), status (ok/failed/pending), and a note. Use this to remember what you shipped when — and to spot clients who have not had a fresh deploy in a while.'},
{id:'demos', title:'Demos', body:'Track every demo URL you have deployed. Cloudflare .pages.dev links you build before a client pays. Demos older than 60 days get flagged for cleanup so you do not accumulate dead links. Click any URL to open it in a new tab.'},
{id:'time', title:'Time', body:'Log hours per client. Unbilled hours accumulate into a $ value at your hourly rate. "Invoice from time" turns all unbilled hours for one client into a single invoice and marks them billed.'},
{id:'scripts', title:'Scripts', body:'Your copy/paste library. Cold call openers, email templates, SMS follow-ups, WhatsApp messages, objection handlers, retainer offers, payment reminders. Edit any title or body inline — autosaves. Copy button puts the filled-in version on your clipboard.'},
{id:'playbook', title:'Playbook', body:'The full Cloudflare-only deployment reference. Account setup, the two-project staging rule, domain + CNAME handling, FormAPI contact forms, Web Analytics, SEO, payments, handover, troubleshooting, pricing. Read this once, then reference it when stuck.'},
{id:'settings', title:'Settings', body:'Your name, brand, rates, package prices, retainer amount, deposit percentage, automation thresholds (staleness, follow-up days, overdue days), proposal terms, cloud sync (JSONBin), data export (JSON + CSV), and the danger zone (reset all data).'},
{id:'search', title:'Command Search', body:'Click the search bar or press / (or Ctrl+K). Prefix characters unlock commands:\n\n+ add — e.g. +lead, +invoice\n- delete — e.g. -client opens a picker\n> go — e.g. >today, >deployments\n/ filter — e.g. /stale, /overdue\n@ source — e.g. @maps filters leads by source\n# stage — e.g. #proposal filters leads by stage\n? help — opens the command reference\n\nPlain text searches across leads, clients, invoices, and proposals.'}
];
